<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-21T13:16:28 IST" name="Default suite" finished-at="2022-11-21T13:17:11 IST" duration-ms="43054">
    <groups>
    </groups>
    <test started-at="2022-11-21T13:16:28 IST" name="Default test" finished-at="2022-11-21T13:17:11 IST" duration-ms="43054">
      <class name="com.bookonelocal.tests.bookingManagement.CreateBookingAndVerifyTheBooking">
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:com.bookonelocal.tests.bookingManagement.CreateBookingAndVerifyTheBooking@24fcf36f]" started-at="2022-11-21T13:16:28 IST" name="initializeDriver" finished-at="2022-11-21T13:16:33 IST" duration-ms="4490" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="createBookingAndVerifyTheBooking(java.util.HashMap)[pri:0, instance:com.bookonelocal.tests.bookingManagement.CreateBookingAndVerifyTheBooking@24fcf36f]" started-at="2022-11-21T13:16:33 IST" name="createBookingAndVerifyTheBooking" data-provider="getData" finished-at="2022-11-21T13:17:11 IST" duration-ms="38215" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{lastName=nanda, numberOfPerson=1, roomTypeName=Single Room, planName=Single Room, numberOfRooms=1, sourceOfBooking=Walk in, searchOptionName=phone, operatorName=satyajit, externalBookingNumber=123456789, arrivalDate=21/11/2022, counterName=Counter 1, firstName=satyajit, phoneNumber=7326954153, numberOfChildren=1, roomNumbers=103, departureDate=22/11/2022, email=satyajitkumar852@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.bookonelocal.tests.bookingManagement.CreateBookingAndVerifyTheBooking.createBookingAndVerifyTheBooking(CreateBookingAndVerifyTheBooking.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createBookingAndVerifyTheBooking -->
      </class> <!-- com.bookonelocal.tests.bookingManagement.CreateBookingAndVerifyTheBooking -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
